import type { Metadata } from "next";

import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css'
import dynamic from "next/dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NavBar = dynamic(() => import('./components/layouts/Navbar'), { ssr: true });
const Footer = dynamic(() => import('./components/layouts/Footer'), { ssr: true });
const Head = dynamic(() => import('./components/layouts/Header'), { ssr: true });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Head/>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
